site_name: QuDirac.jl
repo_url: https://github.com/JuliaQuantum/QuDirac.jl

pages:
- ['index.md', 'Introduction']
- ['bras_and_kets.md', 'Bras and Kets']
- ['states_as_data_structures.md', 'States as Data Structures']
- ['custom_inner_products.md', 'Custom Inner Products']