site_name: QuDirac.jl
repo_url: https://github.com/JuliaQuantum/QuDirac.jl
theme: readthedocs
markdown_extensions: [fenced_code]
pages:
- ['index.md', 'Introduction']
- ['constructing_states.md', 'User Guide', 'Constructing Single States']
- ['d_str.md', 'User Guide', 'd" ... " syntax']
- ['state_math.md', 'User Guide', 'Math with States']
- ['op_math.md', 'User Guide', 'Math with Operators']
- ['labels_and_coeffs.md', 'User Guide', 'Labels and Coefficients']
- ['func_op_def.md', 'User Guide', 'Constructing Operators with Functions']
- ['inner_products.md', 'User Guide', 'Working with Inner Products']
- ['api.md', 'User Guide', 'API']