site_name: QuDirac.jl
repo_url: https://github.com/JuliaQuantum/QuDirac.jl
pages:
- ['index.md', 'Introduction']
- ['states_intro.md', 'States', 'Introduction']
- ['constructing_states.md', 'States', 'Constructing Single Bras and Kets']
- ['state_math.md', 'States', 'Math with States']
- ['analyzing_states.md','States', 'Analyzing States']
- ['custom_inner_products.md', 'States', 'Custom Inner Products']
- ['drc_str.md', 'Misc', 'Natural expression input using @drc_str']
theme: readthedocs